name: Build and Export Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 Docker Hub（如果需要）
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t node-runner:latest .

      # 导出 Docker 镜像到 tar 文件
      - name: Save Docker image as tar
        run: |
          docker save node-runner:latest -o node-runner.tar

      # 上传导出的镜像作为构建工件
      - name: Upload image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-runner
          path: node-runner.tar
