name: Build and Export Docker Image

on:
  workflow_dispatch: # 手动触发事件
    inputs:
      node_version: # 定义 node 版本输入参数
        default: 'alpine' # 提供默认值
        required: true # 确保输入参数是必需的
        description: '请输入 Node Docker 镜像版本！'

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ github.event.inputs.node_version }} # 设置环境变量

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录 Docker Hub（如果需要）
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t node-runner:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .

      # 导出 Docker 镜像到 tar 文件
      - name: Save Docker image as tar
        run: |
          docker save node-runner:$NODE_VERSION -o node-runner-$NODE_VERSION.tar

      # 上传导出的镜像作为构建工件
      - name: Upload image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-runner-$NODE_VERSION
          path: node-runner-$NODE_VERSION.tar
