name: Build node runner
on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      # 定义镜像版本输入参数
      node_version:
        # 镜像版本必填
        required: true
        # 提供镜像版本默认值
        default: alpine
        # 镜像版本参数输入描述
        description: 请输入镜像版本
      # 定义时区输入参数
      host_timezone:
        # 主机时区必填
        required: true
        # 提供主机时区默认值
        default: Asia/Shanghai
        # 主机时区参数输入描述
        description: 请输入主机时区
jobs:
  build node runner:
    runs-on: ubuntu-latest
    env:
      # 设置环境变量
      IMAGE_TAG: 'node-runner:${{ inputs.node_version }}'
      IMAGE_FILE: 'node-runner-${{ inputs.node_version }}.tar'
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      # 初始化 Docker 构建工具
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
      # 构建 Docker 镜像文件
      - name: Build node runner
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            NODE_VERSION=${{ inputs.node_version }}
            HOST_TIMEZONE=${{ inputs.host_timezone }}
          cache-to: type=local,dest=${{ runner.temp }}/.buildx
          cache-from: type=local,src=${{ runner.temp }}/.buildx
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.IMAGE_FILE }}
      # 上传导出的镜像作为构建工件
      - name: Upload node runner
        uses: actions/upload-artifact@v4
        with:
          # 文件保留天数
          retention-days: 1
          name: ${{ env.IMAGE_FILE }}
          path: ${{ runner.temp }}/${{ env.IMAGE_FILE }}
